"""add related stock table

Revision ID: 0a3dca516d11
Revises: 
Create Date: 2026-02-17 14:19:25.162714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0a3dca516d11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices_1m',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('price_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'price_datetime', name='uq_stock_prices_1m_ticker_price_datetime')
    )
    op.create_index(op.f('ix_stock_prices_1m_price_datetime'), 'stock_prices_1m', ['price_datetime'], unique=False)
    op.create_index(op.f('ix_stock_prices_1m_ticker'), 'stock_prices_1m', ['ticker'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_is_active'), 'tickers', ['is_active'], unique=False)
    op.create_index(op.f('ix_tickers_ticker'), 'tickers', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_ticker'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_is_active'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_stock_prices_1m_ticker'), table_name='stock_prices_1m')
    op.drop_index(op.f('ix_stock_prices_1m_price_datetime'), table_name='stock_prices_1m')
    op.drop_table('stock_prices_1m')
    # ### end Alembic commands ###
