"""create stock_prices_1m table

Revision ID: cc5837810f56
Revises: 
Create Date: 2026-02-15 15:17:04.012588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cc5837810f56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices_1m',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'datetime', name='uq_stock_prices_1m_ticker_datetime')
    )
    op.create_index('ix_stock_prices_1m_datetime', 'stock_prices_1m', ['datetime'], unique=False)
    op.create_index('ix_stock_prices_1m_ticker', 'stock_prices_1m', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_prices_1m_ticker', table_name='stock_prices_1m')
    op.drop_index('ix_stock_prices_1m_datetime', table_name='stock_prices_1m')
    op.drop_table('stock_prices_1m')
    # ### end Alembic commands ###
