"""fix stock foreign key

Revision ID: 48b9ce647bd9
Revises: 0a3dca516d11
Create Date: 2026-03-02 12:25:00.704690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '48b9ce647bd9'
down_revision: Union[str, Sequence[str], None] = '0a3dca516d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices_1m', sa.Column('ticker_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_stock_prices_1m_ticker'), table_name='stock_prices_1m')
    op.drop_constraint(op.f('uq_stock_prices_1m_ticker_price_datetime'), 'stock_prices_1m', type_='unique')
    op.create_index(op.f('ix_stock_prices_1m_ticker_id'), 'stock_prices_1m', ['ticker_id'], unique=False)
    op.create_unique_constraint('uq_stock_prices_1m_ticker_id_price_datetime', 'stock_prices_1m', ['ticker_id', 'price_datetime'])
    op.create_foreign_key(None, 'stock_prices_1m', 'tickers', ['ticker_id'], ['id'])
    op.drop_column('stock_prices_1m', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices_1m', sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_prices_1m', type_='foreignkey')
    op.drop_constraint('uq_stock_prices_1m_ticker_id_price_datetime', 'stock_prices_1m', type_='unique')
    op.drop_index(op.f('ix_stock_prices_1m_ticker_id'), table_name='stock_prices_1m')
    op.create_unique_constraint(op.f('uq_stock_prices_1m_ticker_price_datetime'), 'stock_prices_1m', ['ticker', 'price_datetime'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_stock_prices_1m_ticker'), 'stock_prices_1m', ['ticker'], unique=False)
    op.drop_column('stock_prices_1m', 'ticker_id')
    # ### end Alembic commands ###
